# Configuración de Serenity BDD
# Nombre del proyecto en los reportes
serenity.project.name=Wompi Payment API Automation
# Configuración de reportes
serenity.take.screenshots=FOR_FAILURES
serenity.report.encoding=UTF-8
serenity.logging=VERBOSE
# Configuración de REST Assured
restassured.baseurl=https://api-sandbox.co.uat.wompi.dev/v1
# Timeouts
webdriver.timeouts.implicitlywait=5000
# Configuración de testing
serenity.test.root=src/test/java

